## Exploration Notebook

### Setup

In [1]:
import pandas as pd  # noqa
from scipy import stats  # noqa
import seaborn as sns  # noqa
from utils.soda3_client import SOQL_Querying  # noqa
from dotenv import load_dotenv
import os

## Pre Expoloration Setup

### Ridership Exploration

In [2]:
# environment

load_dotenv()
client = SOQL_Querying(
    dataset_url="https://data.ny.gov/api/v3/views/gxb3-akrn/query.json",
    app_token=os.environ["SOCRATA_APP_TOKEN"],
)

In [5]:
latest_data = client.query("select * order by transit_timestamp desc limit 5")
latest_data

,transit_timestamp,bus_route,payment_method,fare_class_category,ridership,transfers
0,2026-09-08T23:00:00.000,B1,omny,Metrocard - Other,0,0
1,2026-09-08T23:00:00.000,B106,metrocard,Metrocard - Seniors & Disability,0,0
2,2026-09-08T23:00:00.000,B12,omny,OMNY - Fair Fares,0,0
3,2026-09-08T23:00:00.000,B17,omny,OMNY - Full Fare,0,0
4,2026-09-08T23:00:00.000,B20,omny,Metrocard - Other,0,0

In [13]:
b82_ridership = client.query("""
    select
        bus_route,
        date_extract_m(transit_timestamp) as month_2025,
        sum(ridership) as total_riders, 
        sum(transfers) as total_transfers 
    where 
        bus_route like '%B82%'
        and 
        date_extract_y(transit_timestamp) = 2025 
    group by
        bus_route,
        date_extract_m(transit_timestamp)
    order by
        bus_route,
        month_2025
    """)

In [14]:
b82_ridership.head(24)

   bus_route month_2025 total_riders total_transfers
0        B82          1       252376           48064
1        B82          2       240985           46669
2        B82          3       276952           54261
3        B82          4       265907           54166
4        B82          5       290251           55581
5        B82          6       280375           62736
6        B82          7       279075           63416
7        B82          8       274749           66235
8        B82          9       271842           63208
9        B82         10       257008           63278
10       B82         11       246009           61728
11       B82         12       239688           63668
12      B82+          1       166578           33022
13      B82+          2       145178           30114
14      B82+          3       168138           36252
15      B82+          4       172254           37086
16      B82+          5       174707           34042
17      B82+          6       175579           41697
18      B82+          7       183414           45244
19      B82+          8       170274           45585
20      B82+          9       171647           43277
21      B82+         10       172354           48178
22      B82+         11       139630           40060
23      B82+         12       148305           43753